#Scrape

---



In [4]:
'''import requests
import pandas as pd

keyword = 'brazil bad news'
api_url = 'https://api.hasdata.com/scrape/google'
headers = {'x-api-key': '70563f6d-f1a6-4570-bcac-470d6f076ffb'}
params = {
    'q': keyword,
    'domain': 'google.com',
    'tbm': 'nws',
    'num': '100',
    'start': '10'
}

try:
    response = requests.get(api_url, params=params, headers=headers)
    if response.status_code == 200:
        data = response.json()
        news = data['newsResults']
        df = pd.DataFrame(news)
        df.to_csv("bad_news_result_.csv", index=False)
except Exception as e:
    print('Error:', e)'''


'import requests\nimport pandas as pd\n\nkeyword = \'brazil bad news\'\napi_url = \'https://api.hasdata.com/scrape/google\'\nheaders = {\'x-api-key\': \'70563f6d-f1a6-4570-bcac-470d6f076ffb\'}\nparams = {\n    \'q\': keyword,\n    \'domain\': \'google.com\',\n    \'tbm\': \'nws\',\n    \'num\': \'100\',\n    \'start\': \'10\'\n}\n\ntry:\n    response = requests.get(api_url, params=params, headers=headers)\n    if response.status_code == 200:\n        data = response.json()\n        news = data[\'newsResults\']\n        df = pd.DataFrame(news)\n        df.to_csv("bad_news_result_.csv", index=False)\nexcept Exception as e:\n    print(\'Error:\', e)'

#Modelo

In [5]:
!pip install transformers

In [6]:
import torch
import torch.nn as nn
from transformers import AutoTokenizer  # Or BertTokenizer
from transformers import AutoModelForPreTraining  # Or BertForPreTraining for loading pretraining heads
from transformers import AutoModel  # or BertModel, for BERT without pretraining heads
import numpy as np

In [7]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
model = BertModel.from_pretrained("bert-base-multilingual-cased")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

In [8]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(119547, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=Fals

In [9]:
meu_modelo = model

In [10]:
meu_modelo

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(119547, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=Fals

In [11]:
model.config

BertConfig {
  "_name_or_path": "bert-base-multilingual-cased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.41.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 119547
}

In [12]:
from transformers import BertPreTrainedModel
from typing import List, Optional, Tuple, Union

In [13]:
class LIABertClassifier(nn.Module):
    def __init__(self,model,num_labels):
        super(LIABertClassifier,self).__init__()
        self.bert = model
        self.config = model.config
        self.num_labels = num_labels
        self.cls = nn.Linear(self.config.hidden_size,200)
        self.dropout = nn.Dropout(p=0.5)
        self.cls2 = nn.Linear(200,num_labels)
        self.gelu = nn.GELU()
        self.join_strategy = 'avg'

    def forward(
        self,
        input_ids: Optional[torch.Tensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        token_type_ids: Optional[torch.Tensor] = None,
        ) ->Tuple[torch.Tensor]:

        outputs = self.bert(
            input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids,
        )
        if self.join_strategy == 'zero':
            sequence_output = outputs[0][:,0,:]
        else:
            last_layer= outputs[0][:,:,:]
            sequence_output = torch.mean(last_layer,dim=1)
        prediction = self.cls(sequence_output)
        prediction = self.gelu(prediction)
        prediction = self.dropout(prediction)
        prediction = self.cls2(prediction)
        return prediction

In [14]:
model = LIABertClassifier(model=meu_modelo,num_labels=2)

In [15]:
model

LIABertClassifier(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elemen

#Dados pelo CSV

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [17]:
import pandas as pd
import os

In [18]:
os.chdir('/content/drive/MyDrive/classifica_datasets')

In [19]:
!ls

dataset.csv


In [22]:
data = pd.read_csv('dataset.csv')

In [23]:
data.head(10)

label                                               text
0      1  Conservation good news: Giant anteaters are re...
1      1  Couple Plants 2 Million Trees in 20 Years to T...
2      1  Brazilian horse ‘Caramelo’ rescued after being...
3      1  Local News: Good news: Leapers & Leaplings (2/...
4      1  The Push for a Better Dengue Vaccine Grows Mor...
5      1  Deforestation hits record low in Brazilian Ama...
6      1  Good News: Doppler Dave shares his incredible ...
7      1          Amazon Deforestation is Down. Here’s Why.
8      1  Pope urges Brazil’s consecrated religious to c...
9      1  Some deserved good news Especially for the horse.

In [24]:
data.describe

<bound method NDFrame.describe of      label                                               text
0        1  Conservation good news: Giant anteaters are re...
1        1  Couple Plants 2 Million Trees in 20 Years to T...
2        1  Brazilian horse ‘Caramelo’ rescued after being...
3        1  Local News: Good news: Leapers & Leaplings (2/...
4        1  The Push for a Better Dengue Vaccine Grows Mor...
..     ...                                                ...
395      0  Political Unrest Escalates: Brazil Faces Worst...
396      0  Economic Meltdown: Brazil Enters Recession as ...
397      0  Healthcare System Collapse: Hospitals in Brazi...
398      0  Violence Epidemic: Crime Rates Soar to Record ...
399      0  Cultural Heritage in Peril: Historic Sites in ...

[400 rows x 2 columns]>

In [25]:
data['label'].value_counts()

label
1    200
0    200
Name: count, dtype: int64

In [26]:
data['text']

0      Conservation good news: Giant anteaters are re...
1      Couple Plants 2 Million Trees in 20 Years to T...
2      Brazilian horse ‘Caramelo’ rescued after being...
3      Local News: Good news: Leapers & Leaplings (2/...
4      The Push for a Better Dengue Vaccine Grows Mor...
                             ...                        
395    Political Unrest Escalates: Brazil Faces Worst...
396    Economic Meltdown: Brazil Enters Recession as ...
397    Healthcare System Collapse: Hospitals in Brazi...
398    Violence Epidemic: Crime Rates Soar to Record ...
399    Cultural Heritage in Peril: Historic Sites in ...
Name: text, Length: 400, dtype: object

In [27]:
shuffle=np.random.randint(0,len(data['text']),1000)

In [28]:
ytrain_global = np.array(data['label'].tolist())[:1000]
xtrain_global = np.array(data['text'])[:1000]

#Dataloader

In [29]:
import sklearn.model_selection as model_selection

In [30]:
xtrain, xval, ytrain, yval = model_selection.train_test_split(xtrain_global, ytrain_global, test_size=0.30, random_state=42,shuffle=True)

In [31]:
for v in zip(xtrain[:3],ytrain[:3]):
    print(v)

('Once nearing extinction, golden lion tamarin monkeys rebound from yellow \nfever outbreak, habitat loss', 1)
('Mongabay CEO discusses slowdown in Amazon loss and other positive news', 1)
('Finally, some good news. Deforestation in the Brazilian Amazon plunges to \nsix-year-low', 1)


In [32]:
train_encodings = tokenizer(xtrain.tolist(), truncation=True, padding=True, max_length=512, return_tensors='pt')
val_encodings = tokenizer(xval.tolist(), truncation=True, padding=True,max_length=512, return_tensors='pt')

In [33]:
train_encodings.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [34]:
train_encodings['input_ids'][0]

tensor([   101,  23075,  12883,  10230,  91253,    117,  52477,  73025,  14918,
         50667,  34372,  25975,  10107,  11639,  47755,  10188,  29815, 105142,
         63831,    117,  24410,  18576,    102,      0,      0,      0,      0,
             0,      0,      0,      0])

In [35]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        label = torch.tensor(self.labels[idx])
        return (item,label)

    def __len__(self):
        return len(self.labels)

In [36]:
ret=train_encodings.items()

In [37]:
ds_train = MyDataset(train_encodings,ytrain)
ds_val   = MyDataset(val_encodings,yval)

In [38]:
np.unique(ytrain,return_counts=True)

(array([0, 1]), array([142, 138]))

In [39]:
from torch.utils.data import DataLoader

In [40]:
dl_train = DataLoader(ds_train,batch_size=8)
dl_eval  = DataLoader(ds_val,batch_size=8)

In [41]:
x,y = next(iter(dl_train))

In [42]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

In [43]:
device

device(type='cuda')

In [44]:
batch = {k: v.to(device) for k, v in x.items()}

In [45]:
model.to(device)

LIABertClassifier(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elemen

In [46]:
out = model(**batch)

In [47]:
out

tensor([[ 0.1067, -0.0078],
        [-0.0885, -0.1356],
        [ 0.0211, -0.0786],
        [ 0.0541,  0.0088],
        [ 0.0392, -0.0870],
        [ 0.0496, -0.2077],
        [ 0.0468,  0.0131],
        [-0.0737, -0.0081]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [48]:
from torch.optim import AdamW
optimizer = AdamW(model.parameters(), lr=1e-5)

In [49]:
from transformers import get_scheduler

In [50]:
num_epochs = 10

In [51]:
loss_fct = nn.CrossEntropyLoss()

In [52]:
for epoch in range(num_epochs):
    lepochs = []
    for batch,y in dl_train:
        batch = {k: v.to(device) for k, v in batch.items()}
        y     = y.to(device)
        outputs = model(**batch)
        loss = loss_fct(outputs,y)
        loss.backward()
        lepochs.append(loss.cpu().item())
        optimizer.step()
        #lr_scheduler.step()
        optimizer.zero_grad()
    print(np.mean(lepochs))

0.6802959680557251
0.5235958439963204
0.1943589674574988
0.11526175742702825
0.06696415596774646
0.05858604298638446
0.05490103780425021
0.04814596930518746
0.04474096024142844
0.045811075896822984


In [53]:
model.eval()

LIABertClassifier(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elemen

In [54]:
ytrue = []
ypred = []
for batch,y in dl_eval:
    batch = {k: v.to(device) for k, v in batch.items()}
    with torch.no_grad():
        outputs = model(**batch)
    predictions = torch.argmax(outputs, dim=-1)
    ytrue += y.tolist()
    ypred += predictions.cpu().tolist()

In [55]:
x,y = next(iter(dl_eval))

In [56]:
batch = {k: v.to(device) for k, v in x.items()}

In [57]:
with torch.no_grad():
    outputs = model(**batch)

In [58]:
outputs

tensor([[ 2.5971, -2.8203],
        [ 2.6136, -2.7856],
        [-3.0596,  2.5106],
        [ 2.6294, -2.8676],
        [-2.9608,  2.2551],
        [-0.8084,  0.1067],
        [ 1.1511, -1.5748],
        [-3.2213,  2.6292]], device='cuda:0')

In [59]:
!pwd

/content/drive/MyDrive/classifica_datasets


#Salvar e carregar modelo

In [60]:
#torch.save(model.state_dict(),'/content/drive/MyDrive/model.pth')

In [61]:
#backup = torch.load('/content/drive/MyDrive/model.pth')

In [62]:
#model.load_state_dict(backup)

#Avaliação do modelo

In [63]:
from sklearn import metrics

In [64]:
metrics.confusion_matrix(ytrue,ypred)

array([[56,  2],
       [ 3, 59]])

In [65]:
print(metrics.classification_report(ytrue,ypred))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96        58
           1       0.97      0.95      0.96        62

    accuracy                           0.96       120
   macro avg       0.96      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120



#Exemplo de classificação de texto

In [372]:
#Good News
token=tokenizer(["Brazil has the best education"],return_tensors='pt')
#token=tokenizer(["Brazil has the best workers"],return_tensors='pt')
#token=tokenizer(["Amazon Rainforest Conservation Efforts Surge, Biodiversity Flourishing"],return_tensors='pt')
#token=tokenizer(["Brazilian Scientists Develop Breakthrough Zika Virus Vaccine"],return_tensors='pt')
#token=tokenizer(["Rio de Janeiro Achieves Record Low Crime Rates During Carnival"],return_tensors='pt')
#token=tokenizer(["Rio de Janeiro Achieves Record Low Crime Rates During Carnival"],return_tensors='pt')
#token=tokenizer(["Amazon Indigenous Communities Gain Land Rights Victory"],return_tensors='pt')
#token=tokenizer(["Brazilian Artists Sweep Grammy Awards"],return_tensors='pt')


#Bad News
#token=tokenizer(["Brazil has the worst workers"],return_tensors='pt')
#token=tokenizer(["Brazil facing dangerous"],return_tensors='pt')
#token=tokenizer(["Brazil has growing poverty"],return_tensors='pt')
#token=tokenizer(["Brazil's Pantanal is on fire"],return_tensors='pt')
#token=tokenizer(["Food Insecurity Crisis: Millions Struggle with Hunger Amidst Economic Woes"],return_tensors='pt')
#token=tokenizer(["Gender-Based Violence Crisis: Calls for Action Against Rising Assaults"],return_tensors='pt')
#token=tokenizer(["Brazil faces health problems"],return_tensors='pt')

In [373]:
out=model(input_ids=token['input_ids'].to(device))

In [374]:
out

tensor([[-0.8987,  0.1294]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [375]:
if torch.argmax(out, dim=-1)[0].cpu().item() == 0:
    print('Bad news from Brazil')
else:
    print('Good news from Brazil')

Good news from Brazil
